"""empty message

Revision ID: c7daaf779609
Revises: 591fcd1876c9
Create Date: 2020-04-28 14:22:01.328054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7daaf779609'
down_revision = '591fcd1876c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))


    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
