"""empty message

Revision ID: c7daaf779609
Revises: 591fcd1876c9
Create Date: 2020-04-28 14:22:01.328054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7daaf779609'
down_revision = '591fcd1876c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # nullable=True just so we can run the script
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    # this call lets us pass SQL command
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    # update the completed column of the todos table to be nullable=False
    # now any records that have already been in the database will still be there, but will have the inital value of false
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
